version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL_API=/api
      - VITE_PROXY_TARGET=http://host.docker.internal:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
