version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL_API=http://localhost:3000
      - VITE_GOOGLE_CLIENT_ID=53270748866-5m51010tidojg0hfpmgqo54l7dpqegb2.apps.googleusercontent.com
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - douglas-barbearia_default
    external_links:
      - api-barbearia-dev

networks:
  douglas-barbearia_default:
    external: true
